app:
  appName: LikeBiliStation
  port: 8080

database:
  dsn: "root:123456@tcp(127.0.0.1:721)/likebili?charset=utf8mb4&parseTime=True&loc=Local"
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600



