ServerName: LikeBiliStation
ServerPort: 8080

DBHost: "127.0.0.1"
DBPort: "721"
DBUser: "root"
DBPassword: "123456"
DBName: "likebili"
MaxIdleConns: 10
MaxOpenConns: 100
ConnMaxLifetime: 3600

RedisHost: "localhost"
RedisAddr: 6379
RedisPassword: ""
RedisDB: 0
RedisTimeout: 7

JWTSecret: "likebili-secret-key"
JWTExpire: 72
