ServerName: LikeBiliStation
ServerPort: 8080

DBHost: "127.0.0.1"
DBPort: "721"
DBUser: "root"
DBPassword: "123456"
DBName: "likebili"
MaxIdleConns: 10
MaxOpenConns: 100
ConnMaxLifetime: 3600

RedisHost: "localhost"
RedisAddr: 6379
RedisPassword: ""
RedisDB: 0

JWTSecret: "likebili-secret-key"
TokenTTLDays: 7


MinioEndpoint: "192.168.11.100:9000"
MinioPublicEndpoint: "192.168.11.100:9000"
MinioAccessKey: "minioadmin"
MinioSecretKey: "minioadmin"
MinioBucket: "likebili"
MinioUseSSL: "false"